'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConsultaMedica
    Public Property id As Integer
    Public Property idCitas As Integer
    Public Property altura As Double
    Public Property peso As Double
    Public Property presion As Double
    Public Property descripcionSintomas As String
    Public Property sintomas As String
    Public Property descripcionProceso As String

    Public Overridable Property Citas As Citas
    Public Overridable Property ExamenOrina As ICollection(Of ExamenOrina) = New HashSet(Of ExamenOrina)
    Public Overridable Property ExamenSangre As ICollection(Of ExamenSangre) = New HashSet(Of ExamenSangre)
    Public Overridable Property MedicamentoRecetado As ICollection(Of MedicamentoRecetado) = New HashSet(Of MedicamentoRecetado)

End Class
