'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Enfermedad
    Public Property id As Integer
    Public Property cedula_paciente As Integer
    Public Property enfermedad1 As String
    Public Property descripcion As String

    Public Overridable Property Paciente As Paciente

End Class
