'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ExamenOrina
    Public Property id As Integer
    Public Property idConsulta As Integer
    Public Property color As String
    Public Property eritrocitos As Integer
    Public Property glucosa As Integer
    Public Property leucocitos As Integer

    Public Overridable Property ConsultaMedica As ConsultaMedica

End Class
