'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ExamenSangre
    Public Property id As Integer
    Public Property idConsulta As Integer
    Public Property acidoUrico As Double
    Public Property creatinina As Double
    Public Property colesterol As Double
    Public Property hematocrito As Double
    Public Property hemoglobina As Double
    Public Property tigliceridos As Double

    Public Overridable Property ConsultaMedica As ConsultaMedica

End Class
