'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonaContacto
    Public Property cedula As Integer
    Public Property nombre As String
    Public Property relacionFamiliar As String
    Public Property telefono As String
    Public Property direccion As String
    Public Property cedPaciente As Integer

    Public Overridable Property Paciente As Paciente

End Class
